### ISSUE TITLE
Need a VOLK release containing #155 ASAP.

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/volk#171]
In order to release GR 3.7.12, I'd need a VOLK release this week.

**Comment by n-west** [comment]
v1.3.1 out in tag

**Comment by marcusmueller** [comment]
Awesome! Thank you!

**Comment by marcusmueller** [comment]
Awesome! Thank you!

**Comment by marcusmueller** [comment]
Nope, sadly have to reopen this: I need #155 in that release :( sorry

**Comment by marcusmueller** [comment]
There's a branch called [apply_PR_#155](https://github.com/gnuradio/volk/tree/apply_PR_%23155); please merge onto maint, and tag appropriately!

**Comment by hcab14** [comment]
Just for my curiosity, why do you tag from maint and not from master?

**Comment by marcusmueller** [comment]
old development model. Last release to do so.

**Comment by n-west** [comment]
I've been doing the merge back model, actually. @hcab14 maint is sort of a longer term support branch because some people really need a stable API more than they need new features. To accommodate that I make everything go on master, cherry-pick bug fixes back to maint. In theory maint is released every so often and people can safely update with confidence of getting bug fixes and not broken code/dependencies.  "major releases" happen less frequently off of master and include new features. In practice I don't have as strict a release schedule as I should and have recently been lazy about releases.

**Comment by n-west** [comment]
Released v1.4!
