### ISSUE TITLE
Using the Intel Software Development Emulator for CI tests

### ISSUE THREAD

**Issue by hcab14** [gnuradio/volk#216]
Continuing the discussion from https://github.com/gnuradio/volk/pull/190#issuecomment-425729635: would it be possible to put the Intel SDE file e.g. on the gnuradio webserver?

For a similar discussion see https://github.com/shibatch/sleef/issues/85

**Comment by jdemel** [comment]
It seems like they could solve their license concerns. @jeffhammond helped them out.
Basically, they use a Travis secure environment variable to hide the URL where they download SDE from. We need to confirm that this approach is the way to go and that it is covered by the SDE license. Then we need to figure out where our URL variable points to. Finally, we need to integrate this into our CI tests. Maybe we use a distinct test for this configuration since it runs way longer than without SDE.

**Comment by jeffhammond** [comment]
There is a better to do it now.  See https://github.com/mmcloughlin/meow/blob/871e50784daff1c9ec5ef66fe3d8fda6bbcd42cf/.travis.yml.  This is not my work.  BLIS uses this method now (https://github.com/flame/blis/blob/master/travis/do_sde.sh).

**Comment by hcab14** [comment]
Is this way of having the Intel emulator acceptable? If yes I'll go ahead and make a pull request.

**Comment by jeffhammond** [comment]
I am not a lawyer and cannot tell you what is acceptable.

**Comment by michaelld** [comment]
Closed via #304
