### ISSUE TITLE
Problem with POLAR encoding/decoding blocks

### ISSUE THREAD

**Issue by armin485** [gnuradio/volk#414]
It seems newer version of volk got issue with POLAR encoding/decoding blocks as well.
if you open examples in gr-fec/examples/polar_code_example.grc & fecapi_polar_decoders.grc you can observe that source info bits and decoded bits are not same.
it seems the bug comes from the same point because #395 and #3376 in gnuradio git have same issues.
workaround as other issues with same effect:
1. run volk_profile
2. change volk_8u_x3_encode_polar_8u_x2 in ~/.volk/volk_config to generic generic
3. restart gnuradio

**Comment by jdemel** [comment]
@armin485 in VOLK convolutional and polar functions are completely separate. I'd assume it's only a coincidence that they manifest in the kind of issue in GR. 
What was  ` volk_8u_x3_encode_polar_8u_x2 generic generic` before you updated it? Could you test this with other kernel options as well?

**Comment by argilo** [comment]
I noticed this as well: https://github.com/gnuradio/volk/issues/356#issuecomment-590150158

In fact, if `VOLK_GENERIC=1` is removed from GNU Radio's test suite, then the `qa_polar_decoder_sc_systematic` test begins failing because the AVX2 polar implementation produces incorrect results when the block size is 16 (the value used in the test).

**Comment by argilo** [comment]
Fix: #642
