### ISSUE TITLE
Poor random numbers in uint tests.

### ISSUE THREAD

**Issue by jsallay** [gnuradio/volk#688]
https://github.com/gnuradio/volk/blob/main/lib/qa_utils.cc#L54  Contains: `float int_max = float(uint64_t(2) << (type.size * 8));`.  If `type.size` is 8, then `int_max = uint64_t(2) << 64`.  Shift a 64-bit number by 64 is undefined behavior.  It appears that gcc masks the shift amount and no shift is performed.  Thus the random numbers generated are between 0 and 2 for unsigned 64-bit numbers and -1 and 1 for signed 64-bit numbers.

This is not ideal and causes some tests to not actually exercise algorithm.  See   https://github.com/gnuradio/volk/issues/605

**Comment by jdemel** [comment]
This line is part of:
https://github.com/gnuradio/volk/blob/e853e9bb5693c7800840b736e77db52d713d553e/lib/qa_utils.cc#L41

My idea to fix this issue would be: 
1. Implement another function for every type
2. Add an optional seed for reproducible results
3. Call the specialized functions from `load_random_data`

The structure is created here:
https://github.com/gnuradio/volk/blob/e853e9bb5693c7800840b736e77db52d713d553e/lib/qa_utils.cc#L123

And this is
https://github.com/gnuradio/volk/blob/e853e9bb5693c7800840b736e77db52d713d553e/lib/qa_utils.h#L25-L32

Some templating may reduce the number of specific functions. 

This issue is related to #326 .
